### ISSUE TITLE
Ошибка при импорте в 0.8.1

### ISSUE THREAD

**Issue by xaoc2007** [intervolga/intervolga.migrato#6]
Спасибо за обновление! 

Но возникла такая ошибка при импорте(ниже лог). Похоже модуль iblock недоступен для migrato.

```
Выполняется команда XML => БД (данные и настройки)
--------------------------------------------------------------------------------
[info] Сайт закрыт
--------------------------------------------------------------------------------
[info] Сайт открыт
При выполнении команды произошла ошибка (Класс: Error)
Class 'Bitrix\Iblock\IblockTable' not found (Код ошибки: 0)
Стек вызова:
## .../modules/intervolga.migrato/lib/tool/console/command/reindexfacetcommand.php(88)
#0 .../modules/intervolga.migrato/lib/tool/console/command/reindexfacetcommand.php(34): Intervolga\Migrato\Tool\Console\Command\ReIndexFacetCommand::getIblockIdsByFilter(Array)
#1 .../modules/intervolga.migrato/lib/tool/console/command/importcommand.php(32): Intervolga\Migrato\Tool\Console\Command\ReIndexFacetCommand::saveActiveFacet()
#2 .../modules/intervolga.migrato/lib/tool/console/command/basecommand.php(57): Intervolga\Migrato\Tool\Console\Command\ImportCommand->executeInner()
```

**Comment by arkanif** [comment]
Добрый день!

Уточните, какая версия БУС.

**Comment by xaoc2007** [comment]
17.0.15
редакция Стандарт

**Comment by arkanif** [comment]
Помогает подключение модуля iblock в init.php сайта?

**Comment by xaoc2007** [comment]
Помогает )
Причем на редакции Бизнес проблемы как будто нет. Завтра могу подробнее написать.

**Comment by arkanif** [comment]
Исправлено в 0.8.2
